version: '3'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: ncherlijj11/taski_backend
    env_file: .env
    depends_on:
      - db    
    volumes:
      - static_volume:/backend_static
  frontend:
    image: ncherlijj11/taski_frontend  
    env_file: .env
    depends_on:
      - db    
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: ncherlijj11/taski_gateway 
    env_file: .env
    depends_on:
      - backend
      - frontend      
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80